apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
    name: mfe
    region: us-east-1
nodeGroups:
    - name: ng-1
      minSize: 1
      maxSize: 2
      desiredCapacity: 1
      volumeSize: 10
      availabilityZones: ["us-east-1a","us-east-1b"]
      iam:
        withAddonPolicies:
          imageBuilder: true
          albIngress: true
          autoScaler: true
          appMesh: true
          xRay: true
          cloudWatch: true
          externalDNS: true
      instancesDistribution:
        maxPrice: 0.50
        instanceTypes: ["t2.medium"] # At least one instance type should be specified
        onDemandBaseCapacity: 0
        onDemandPercentageAboveBaseCapacity: 50
        spotInstancePools: 2
